##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   [top-level] (internal): just pass-through "npm install" operation
post-install
    npm --prefix plugin install && \
    npm --prefix tool   install

#   [top-level] lint project
lint
    npm --prefix plugin start lint && \
    npm --prefix tool   start lint

#   [top-level] build project
build
    npm --prefix plugin start build && \
    npm --prefix tool   start build

#   [top-level] publish new release of project
publish [hostname=en4.*]
    npm --prefix plugin start lint && \
    npm --prefix tool   start lint && \
    bump="R"; \
    case "$*" in -b* ) bump=`echo "$*" | sed -e 's;^-i;;'` ;; esac; \
    node etc/version.mts "$bump" && \
    npm --prefix plugin start build && \
    npm --prefix tool   start build && \
    version="$(qq -r .version package.json)"
    git commit \
        -m "update version to $version" \
        package.json \
        tool/package.json \
        plugin/package.json \
        plugin/.claude-plugin/plugin.json \
        plugin/.github/plugin/plugin.json && \
    git tag "$version" && \
    git push && \
    git push --tags && \
    (cd tool && npm publish) && \
    V=`echo "$version" | sed -e 's;\.;\\.;g'` && \
    sed -n -e "/^${V} /, /^[0-9]\\./ { /^${V} /p; /^[0-9]\\./!p; }" <CHANGELOG.md >.notes.md && \
    gh release create --title "ASE $version" --notes-file .notes.md --verify-tag $version && \
    rm -f .notes.md

#   [top-level] remove regularly built files
clean
    npm --prefix plugin start clean && \
    npm --prefix tool   start clean && \
    shx rm -rf dst

#   [top-level] remove all built files
distclean: clean
    npm --prefix plugin start distclean && \
    npm --prefix tool   start distclean && \
    shx rm -f package-lock.json && \
    shx rm -rf node_modules

